version: "3"

services:
    gl-mongo-express:
        image: mongo-express:0.54.0
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: gl-mongo
            ME_CONFIG_BASICAUTH_USERNAME: devontherun
            ME_CONFIG_BASICAUTH_PASSWORD: 123mudar
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123mudar
        depends_on:
            - gl-mongo

    gl-mongo:
        image: mongo:4.0.24
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123mudar
        ports:
            - 27017:27017
        volumes:
            - ./images/mongo/db:/data/db

    gl-node:
        build: ./images/node
        volumes:
            - ./backend:/usr/src/app
            - ./backend/node_modules:/usr/src/app/node_modules
        depends_on:
            - gl-mongo

    gl-nginx:
        build: ./images/nginx
        ports:
            - 8080:80
        depends_on:
            - gl-node
